[package]
name = "leveldb-test"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

leveldb = "0.8.6"
tempdir = "0.3.7"